### ISSUE TITLE
/course/{id} - work tracker

### ISSUE THREAD

**Issue by NiloCK** [NiloCK/vue-skuilder#143]
## Course Dashboards

- [ ] enable site/q/course_title routing
  - [ ] disambiguation page where title collisions exist go (programming language) vs go (board game)
  - [ ] ... disabling q/course_id routing?
- [ ] card browser
  - [ ] plain-text view functions
  - [ ] bulk data requests
  - [ ] sort-by
    - [ ] rating
    - [ ] tag
    - [ ] search term
- [ ] tag browser
  - [x] display tags
  - [ ] tag page
    - [ ] add editing for tag snippets, wiki
    - [ ] insert a filtered card-browser
      - [ ] ... with ability to browse other content for adding the current tag?
- [ ] activity dashboard with, eg,
  - [ ] recently added cards
  - [ ] course "problem" surfacing
  - [ ] heatmap?
