### ISSUE TITLE
deployment scripts work tracker

### ISSUE THREAD

**Issue by NiloCK** [NiloCK/vue-skuilder#144]
Current server configuration is undocumented and requires digging around for clues (location of config files, runners for services, etc) on each update.

- [x] document workings of DO droplet in a readme
- [x] put configuration files (caddyfile, systemd config file) under version control (/.deployment folder?)
- [x] add config files to GH action deployment script
- [ ] add a service restart for express app on deploy
- [x] add a caddy restart on changes to the Caddyfile
- [x] make the GH action deployments dependent on changes to individual components (ie, updates the vue spa should not cause a redeploy of the express app or restart of the express service)

related pre-work: express app is currently building multiple files and depends on a separate node_modules folder. Deployment would be simpler if it built to a single concatenated app.js

- [ ] build express app into single file... OR
- [ ] rebuild node_modules on server depending on changes to yarn.lock or package.json

**Comment by NiloCK** [comment]
basic CI and deployment scripts have been live for a while.
