### ISSUE TITLE
Work Tracker - Content Authoring / Editing

### ISSUE THREAD

**Issue by NiloCK** [NiloCK/vue-skuilder#145]
Courses should have:

- [ ] a configurable `default type` for adding new content
  - [ ] step: make `blanks` the default type for all types first
- [ ] Reinstate `edit` on existing content
