### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by NiloCK** [NiloCK/vue-skuilder#66]
## Non-domain-problems:
- [ ] Rig up an email service (sendgrid?) as a user authentication step, and to enable password resets
- [ ] Fix project config to allow code splitting. Specifically, per-course bundles
- [ ] Look at a-la-cart imports of some dependencies (lodash, vuetify). (Current Bundle size is outrageous: ~5MB)
  - [ ] vuetify-loader ?
- [ ] Internationalization on hard-coded site copy
- [ ] Pick up .org domain?
- [ ] compliance / cya
  - [ ] cookie warnings
  - [ ] TOS
  - [ ] privacy policy
  - [ ] email opt-outs
  - [ ] anything else?

### User facing:
- [x] Improve course browse page - cards w/ indicative course statistics 
- [ ] Internationalization on community content?
 - Will require a re-write of most text-based input types
 - Difficult to enforce on media-based content (picture of text, video, etc)
 - May not be an appropriate use of time
- [x] Enable user input-splitting
- [x] Enable hard-coded datashape inputs
  - [x] (Optionally) Disable user-input when hard-coded inputs provided
- [ ] Per-quilt discussion forum
  - Is it easy to have a drop-in solution here? (discourse, etc)
  - May be difficult to integrate wiith site / quilt data
- [ ] Quilt Requests-for-contribution (toMake) queues
- [ ] Build / improve inputs for audio / video / markdown inputs
### Engine: 
- [ ] Define a query language for pedagogical assertions
- [ ] Define a DI scheme for scheduling agents
- [ ] Quilt problem-surfacing (-> becomes user-facing afterwards)

## Content Goals (exemplar course(s))
- [ ] Piano Course
  - [x] 'PlayNote' type
  - [ ] 'PlayInterval' type
  - [ ] Identify Chord / Scale types - (hard coded data inputs)
- [ ] Doomsday algorithm course
